# These are supported funding model platforms

github: [xeurun] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: xeurun # Replace with a single Patreon username
open_collective: xeurun # Replace with a single Open Collective username
ko_fi: xeurun # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.me/xeurun # Replace with a single custom sponsorship URL
