version: '3.6'

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}-node
    command:  ["npm", "run", "start"]
    build:
      context: .docker
      dockerfile: node.Dockerfile
      args:
        VERSION: 12-alpine
        DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR}
    environment:
      TIMEZONE: Europe/Moscow
    networks:
      - public
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./:${DOCKER_PROJECT_DIR}

networks:
  public:
    external: true
    name: public
