version: '3.6'
networks:
  public:
    external: true
    name: public

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}-node
    build:
      context: .docker
      dockerfile: Dockerfile-node
      args:
        VERSION: 10-alpine
        HTTP_PORT: ${HTTP_PORT}
    environment:
      PW: app
    entrypoint: ["http-server", "-p", $HTTP_PORT]
    networks:
      - public
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    volumes:
      - .:/app
