version: "3"

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}-node
    command: sleep 365d
    build:
      context: .docker
      dockerfile: node.Dockerfile
      args:
        VERSION: 12.9-alpine
    environment:
      TIMEZONE: Europe/Moscow
      NODE_PORT: ${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/workspace
