version: '3.6'
networks:
  public:
    external: true
    name: public

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}-node
    build:
      context: .docker
      dockerfile: Dockerfile-node
      args:
        VERSION: 8-alpine
        NODE_PORT: ${NODE_PORT}
    environment:
      TZ: Europe/Moscow
      PW: /app
    networks:
      - public
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/app
