version: '3.6'

services:
  node:
    container_name: ${DOCKER_PROJECT_NAME}-node
    build:
      context: .docker
      dockerfile: node.Dockerfile
      args:
        VERSION: 10-alpine
        NODE_PORT: ${NODE_PORT}
        DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR}
    environment:
      TZ: Europe/Moscow
      PW: /app
    networks:
      - public
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:${DOCKER_PROJECT_DIR}

networks:
  public:
    external: true
    name: public
