ARG VERSION
ARG NODE_PORT

FROM node:${VERSION} as node

ENV PW=/app
WORKDIR $PW

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

RUN apk update \
    && apk upgrade \
    && apk add --no-cache make git

RUN npm install -g -f npm fsevents

EXPOSE ${NODE_PORT}

CMD ["npm", "run", "dev"]
